version: '3.2'
services:
    nginx:
        image: ngx-server
        build:
            context: .
            dockerfile: nginx.Dockerfile

        depends_on:
            - backend
            - frontend
        ports:
            - 5000:80

    backend:
        image: backend
        environment:
            - PYTHONBUFFERED=0
        build:
            context: .
            dockerfile: backend.Dockerfile

        volumes:
            - type: bind
              source: ./backend
              target: /app

        command: adev runserver main.py --port 8080


    frontend:
        image: frontend
        build:
            context: .
            dockerfile: frontend.Dockerfile
        volumes:
            - type: bind
              source: ./frontend/src
              target: /app/src
        working_dir: /app
        command: npm run start

volumes:
    static_assets:
